api_thug:
    build: ./
    ports:
        - "8003:8000"
    volumes:
        - ./app:/app:rw
        - ./log:/logs:rw
    links:
        - api_mongo
api_mongo:
    container_name: api_thug_mongo
    image: sameersbn/mongodb:latest
    ports:
        - "27272:27017"
    volumes:
        - /data:/var/lib/mongodb:rw
        - /data/log:/var/log/mongodb
    restart: always